[package]
name = "lib-router-api"
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true

[lints]
workspace = true
