[package]
name = "lib-web-router"
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
lib-data-web.workspace = true

axum.workspace = true

[lints]
workspace = true
